Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/ee_train.py", line 147, in <module>
    train_loader, val_loader, test_loader = get_data_loaders(dataset=args.dataset, batch_size=args.batch_size, threads=args.n_workers, 
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 1003, in get_data_loaders
    train_set, val_set, test_set,  _, _ = get_dataset(dataset, augmentation=augmentation, resolution=img_size, val_split=val_split)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/train_utils.py", line 926, in get_dataset
    train_set = datasets.Imagenette('../datasets/imagenette/train', split='train', size='160px', download=False, transform=train_transform)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/env/lib/python3.12/site-packages/torchvision/datasets/imagenette.py", line 70, in __init__
    raise RuntimeError("Dataset not found. You can use download=True to download it.")
RuntimeError: Dataset not found. You can use download=True to download it.
Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/cnas.py", line 349, in _evaluate
    stats = json.load(open(os.path.join(gen_dir, "net_{}/net_{}.stats".format(i,i))))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'results/search_edanas_imagenette/iter_0/net_0/net_0.stats'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Pittorino/workspace/CNAS/cnas.py", line 785, in <module>
    main(cfgs)
  File "/home/Pittorino/workspace/CNAS/cnas.py", line 686, in main
    engine.search()
  File "/home/Pittorino/workspace/CNAS/cnas.py", line 126, in search
    stats = self._evaluate(arch_doe, it=0)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Pittorino/workspace/CNAS/cnas.py", line 355, in _evaluate
    shutil.copy(os.path.join(gen_dir, "net_{}/net_{}.subnet".format(i)),
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Replacement index 1 out of range for positional args tuple
